### ISSUE TITLE
Vellum type error

### ISSUE THREAD

**Issue by azhard4int** [vellum-ai/vellum-python-sdks#49]
Hi there,

We are using Python 3.12, and when we start the project with vellum-ai sdk installed, getting this error.

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/azhar/Dev/blog-genius/backend/venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/azhar/Dev/blog-genius/backend/venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/azhar/Dev/blog-genius/backend/venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/azhar/Dev/blog-genius/backend/venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/azhar/Dev/blog-genius/backend/venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azhar/Dev/blog-genius/backend/venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/azhar/Dev/blog-genius/backend/app/main.py", line 20, in <module>
    from app.api.v1.endpoints.workspace import (
  File "/Users/azhar/Dev/blog-genius/backend/app/api/v1/endpoints/workspace/workspace_actions.py", line 77, in <module>
    from app.core.concerns.vellum_workflows import VellumWorkflowsWrapper
  File "/Users/azhar/Dev/blog-genius/backend/app/core/concerns/vellum_workflows.py", line 1, in <module>
    from vellum.client import Vellum
  File "/Users/azhar/Dev/blog-genius/backend/venv/lib/python3.12/site-packages/vellum/__init__.py", line 3, in <module>
    from .types import (
  File "/Users/azhar/Dev/blog-genius/backend/venv/lib/python3.12/site-packages/vellum/types/__init__.py", line 37, in <module>
    from .chat_message_prompt_block_properties_request import ChatMessagePromptBlockPropertiesRequest
  File "/Users/azhar/Dev/blog-genius/backend/venv/lib/python3.12/site-packages/vellum/types/chat_message_prompt_block_properties_request.py", line 34, in <module>
    update_forward_refs(ChatMessagePromptBlockPropertiesRequest)
  File "/Users/azhar/Dev/blog-genius/backend/venv/lib/python3.12/site-packages/vellum/core/pydantic_utilities.py", line 190, in update_forward_refs
    model.update_forward_refs()
  File "pydantic/main.py", line 814, in pydantic.main.BaseModel.update_forward_refs
  File "pydantic/typing.py", line 559, in pydantic.typing.update_model_forward_refs
  File "pydantic/typing.py", line 525, in pydantic.typing.update_field_forward_refs
  File "pydantic/typing.py", line 68, in pydantic.typing.evaluate_forwardref
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/typing.py", line 952, in _evaluate
    self.__forward_value__ = _eval_type(
                             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/typing.py", line 430, in _eval_type
    ev_args = tuple(
              ^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/typing.py", line 431, in <genexpr>
    _eval_type(
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/typing.py", line 415, in _eval_type
    return t._evaluate(globalns, localns, type_params, recursive_guard=recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/typing.py", line 952, in _evaluate
    self.__forward_value__ = _eval_type(
                             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/typing.py", line 430, in _eval_type
    ev_args = tuple(
              ^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/typing.py", line 431, in <genexpr>
    _eval_type(
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/typing.py", line 415, in _eval_type
    return t._evaluate(globalns, localns, type_params, recursive_guard=recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/typing.py", line 947, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'ChatMessagePromptBlockRequest' is not defined. Did you mean: 'ChatMessagePromptBlockPropertiesRequest'?
```

**Comment by dvargas92495** [comment]
Is this an issue you're still seeing in the latest version of the package?

**Comment by dvargas92495** [comment]
Going to close this issue - happy to reopen if it's still a problem on `0.13.3`
